### ISSUE TITLE
Type checker throwing an error in Eclipse

### ISSUE THREAD

**Issue by rodinaarssen** [usethesource/rascal-core#4]
On every save, `rascal_eclipse` logs an error in Eclipse's error log with the message `Rascal type check failed (check)` and the following stack trace:

```
org.rascalmpl.interpreter.staticErrors.UndeclaredVariable: Undeclared variable: asubtype
Advice: |http://tutor.rascal-mpl.org/Errors/Static/UndeclaredVariable/UndeclaredVariable.html|
	at RascalConfig.?(/C:/Users/310263173/bin/eclipse-photon/configuration/org.eclipse.osgi/833/0/.cp/jars/rascal-core-0.3.0-20190810.131544-12.jar!/src/org/rascalmpl/core/library/lang/rascalcore/check/RascalConfig.rsc:354)
	at org.rascalmpl.semantics.dynamic.Expression$QualifiedName.interpret(Expression.java:2108)
	at org.rascalmpl.semantics.dynamic.Expression$CallOrTree.interpret(Expression.java:511)
	at org.rascalmpl.semantics.dynamic.Statement$Expression.interpret(Statement.java:365)
	at org.rascalmpl.semantics.dynamic.Statement$Return.interpret(Statement.java:783)
	at org.rascalmpl.interpreter.result.RascalFunction.runBody(RascalFunction.java:383)
	at org.rascalmpl.interpreter.result.RascalFunction.call(RascalFunction.java:292)
	at org.rascalmpl.semantics.dynamic.Expression$CallOrTree.interpret(Expression.java:531)
	at org.rascalmpl.semantics.dynamic.Expression$CallOrTree.interpret(Expression.java:493)
	at org.rascalmpl.semantics.dynamic.Statement$Expression.interpret(Statement.java:365)
	at org.rascalmpl.semantics.dynamic.Statement$Assignment.interpret(Statement.java:205)
	at org.rascalmpl.interpreter.result.RascalFunction.runBody(RascalFunction.java:383)
	at org.rascalmpl.interpreter.result.RascalFunction.call(RascalFunction.java:322)
	at org.rascalmpl.interpreter.result.AbstractFunction.call(AbstractFunction.java:206)
	at org.rascalmpl.interpreter.Evaluator.call(Evaluator.java:665)
	at org.rascalmpl.interpreter.Evaluator.call(Evaluator.java:649)
	at org.rascalmpl.interpreter.Evaluator.call(Evaluator.java:459)
	at org.rascalmpl.core.ide.RascalCodeIDEBuilder.lambda$1(RascalCodeIDEBuilder.java:80)
	at org.rascalmpl.core.ide.RascalCodeIDEBuilder.lambda$0(RascalCodeIDEBuilder.java:49)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.rascalmpl.eclipse.builder.IncrementalRascalBuilder.buildChangedModules(IncrementalRascalBuilder.java:398)
	at org.rascalmpl.eclipse.builder.IncrementalRascalBuilder.buildDirty(IncrementalRascalBuilder.java:369)
	at org.rascalmpl.eclipse.builder.IncrementalRascalBuilder.buildIncremental(IncrementalRascalBuilder.java:354)
	at org.rascalmpl.eclipse.builder.IncrementalRascalBuilder.access$2(IncrementalRascalBuilder.java:336)
	at org.rascalmpl.eclipse.builder.IncrementalRascalBuilder$3.run(IncrementalRascalBuilder.java:174)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2289)
	at org.rascalmpl.eclipse.builder.IncrementalRascalBuilder.build(IncrementalRascalBuilder.java:184)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:795)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:216)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:259)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:312)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:315)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:367)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:388)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:142)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
```

**Comment by jurgenvinju** [comment]
I believe rascal-core was left with a static error in it, but since rascal-core isn't automatically compiled yet or tested automatically this is only noticed at run-time. 

From the error message:
   * `Undeclared variable: asubtype`
   * `src/org/rascalmpl/core/library/lang/rascalcore/check/RascalConfig.rsc:354`

**Comment by jurgenvinju** [comment]
* `asubtype` seems to be in scope via a module `extend`;
* the assignment is a field assignment. it could be that data declarations and the processing of extending the module are racing for attention in the interpreter;
* hypothesis: never before a function from an extended module was necessary for declaring a data constructor?

**Comment by jurgenvinju** [comment]
I tried loading the module in a normal REPL in Eclipse an that code simply works. The resolution of `asubtype` succeeds normally, although it has one resolved overloaded alternative with an `unknown:///` location. So it seems this goes wrong somewhere in the search path of the Evaluator we use in the maven Rascal Mojo? (previous hypothesis=rejected)

**Comment by jurgenvinju** [comment]
ah...

```
[INFO] [WARNING] |rascalcore:///lang/rascalcore/check/ComputeType.rsc|(83,38,<5,0>,<5,38>): Could not load lang::rascalcore::check::AType due to: The Tree data-type from the ParseTree library module is "final"; it can not be extended. Please choose another name.
```

**Comment by jurgenvinju** [comment]
after installing the new unstable plugins, this behavior should return to normal. thanks for the report, I would have never noticed.
